### ISSUE TITLE
Chapter 2 Exercise #1

### ISSUE THREAD

**Issue by sean-atkinson** [aloctavodia/BAP3#1]
I’m in need of some clarification on Chapter 2, Exercise #1: are the beta parameters in question from page 34 (Code 1.6), or are they referenced elsewhere? 

It wasn’t entirely clear to me. 

Thanks!

**Comment by aloctavodia** [comment]
Yes, use the values in Code 1.6 and "plug" them in "our_first_model" (Code 2.2)

**Comment by sean-atkinson** [comment]
Perfect. 

Thanks for the quick response!
