### ISSUE TITLE
Chapter 2: Savage Dickey Density Ratio

### ISSUE THREAD

**Issue by stuartvkerr** [aloctavodia/BAP3#10]
Executing Code 2.7 I get the following error:
`AttributeError: module 'nutpie' has no attribute 'random'`

**Comment by stuartvkerr** [comment]
I want to thank you for updating PAWB. I am learning so much. 
You are correct. I did `import nutpie as np` and did `import numpy as np1`. Which is strange because i always import numpy as np. I think the Google Colab AI completed the import statements for me!
Thank you again.

**Comment by aloctavodia** [comment]
Do you mean BAP (Bayesian Analysis with Python)? 

Great that is working now, autocomplete can get in the middle sometimes.

**Comment by stuartvkerr** [comment]
Yes, BAP.
