### ISSUE TITLE
Please explain what is the Bernoulli distribution

### ISSUE THREAD

**Issue by parrenin** [aloctavodia/BAP3#14]
Thank you for this very interesting book that opened my mind to Bayesian statistics!
One small feedback I want to give is regarding the Bernoulli distribution.
This distribution is introduced in code 2.2 p. 52, but its relationship with the Binomial distribution is not clearly explained.
Of course, it is possible to understand what is Bernoulli with a small search on Wikipedia, but I thought for completeness, it would be good to say it in a sentence in the book.

**Comment by aloctavodia** [comment]
Thanks for the feedback! 

I will add a note to the latex source to I can address this in the next edition.
