### ISSUE TITLE
Pg 105 typo

### ISSUE THREAD

**Issue by jjw3952** [aloctavodia/BAP3#20]
Page 105 states

> ... will need to properly index the vectors $\mu_p$ and $\nu_p$ to match the total number of players

 but I believe "players" should be changed to "positions"

**Comment by kenjioman** [comment]
I think this statement is ok as I think it's referring to the `𝜇_p[pos_idx]` and `𝜈_p[pos_idx]` in the code block and (I could be wrong since going off of memory) I think the length of `pos_idx` will be the same as the total # of players.
