### ISSUE TITLE
pg 133 "model interactions"

### ISSUE THREAD

**Issue by jjw3952** [aloctavodia/BAP3#21]
On pg 133 is states, "We have been using the linear motif to model the mean of a distribution and, in the previous section, we used it to model interactions."

Interactions have not been introduced to this point. Not sure if this is a typo and it's supposed to say something else like probably, or if it's a holdover from a previous version where interactions were previously discussed.

**Comment by aloctavodia** [comment]
Hi, thanks for reporting this and the other issues. You are right, this is a  holdover from a previous version.

 I will create an errata for this and the other issues.

**Comment by jjw3952** [comment]
Really enjoying the book so far!
