### ISSUE TITLE
Kurtosis on page 23, third edition

### ISSUE THREAD

**Issue by nsingh-phd** [aloctavodia/BAP3#26]
kurtosis shown in the figure 1.9 is not the actual kurtosis but the "excess kurtosis" which is the kurtosis relative to a normal distribution. the normal distribution has a kurtosis of 3. this figure shows it as zero which you get if you subtract 3. same is true for other shown distributions as well. it should be corrected in the text.

**Comment by aloctavodia** [comment]
Yes, preliz uses the excess kurtosis.
