### ISSUE TITLE
Chapter 1 ex 7, unclear & preliz "error" in solution

### ISSUE THREAD

**Issue by chimicke** [aloctavodia/BAP3#33]
To me, before looking at the solution, it wasn't clear what the goal of the exercise was. Since this is all quite new it would have helped me if it said something along the lines of "_Draw_ samples of different sizes _from a SkewNormal distribution with parameters you choose_, with sizes like 10, 100 and 1000, and see ..."

For me the solution of the ipynb on github didn't work. I got an error on "skn.rv_frozen.stats("mv")": AttributeError: 'SkewNormal' object has no attribute 'rv_frozen'

Using skn.moments("mv") did work.

I'm using preliz version 0.8.1, which is currently the latest version (not 0.3.6 as listed in the book)

**Comment by aloctavodia** [comment]
Added a note for future editions. 

New packages often introduce changes in syntax, especially new ones like PreliZ. My recommendation is to create an environment as explained in the book. But it's fine if you want to use more recent versions, just be prepared to make some adjustments or check the documentation. Actually, checking the documentation is always a good idea!
