### ISSUE TITLE
Errata - Binomial coefficient typeset incorrectly

### ISSUE THREAD

**Issue by cmhh** [aloctavodia/BAP3#36]
On page 13, for example, the binomial coefficient is typeset as $\left(\frac{n}{x}\right)$, but it should just be $\left(n\atop{}x\right)$.  This appears in two places--in the formula for the beta-binomial distribution, and in the paragraph below.

**Comment by aloctavodia** [comment]
Thanks, this has been fixed on the source and added to the errata.
