### ISSUE TITLE
Exercise Solution

### ISSUE THREAD

**Issue by mikeybellissimo** [aloctavodia/BAP3#39]
Hi Just wanted to see if there were any plans to add solutions to exercises beyond Chapter 3 anywhere so we could check our work.
Loving the book by the way thanks for the great work!

**Comment by aloctavodia** [comment]
Thanks for the kind words. I just added solutions to Chapter 4' exercises. I will try to add the rest soon.

**Comment by mikeybellissimo** [comment]
Awesome thanks so much!
