### ISSUE TITLE
preliz: name 'FloatSlider' 

### ISSUE THREAD

**Issue by riversandrew36** [aloctavodia/BAP3#6]
![Screenshot 2024-02-26 at 5 42 54 PM](https://github.com/aloctavodia/BAP3/assets/16710521/6f2d97a9-8015-49a2-8959-eda04a7f43c8)

Using VSCode I'm getting this error but while using colab notebooks everything seems fine. I'm on a Mac computer
Any help would be appreciated.

**Comment by aloctavodia** [comment]
Which version of preliz are you using?

**Comment by riversandrew36** [comment]
preliz==0.3.6

**Comment by aloctavodia** [comment]
You need to install ipywidgets. This is installed if you use the bap3.yml environment. But I now realize this will not be installed by default if you follow the pip install instructions. See https://preliz.readthedocs.io/en/latest/#installation.
